### ISSUE TITLE
cannot load such file -- sinatra/base (LoadError)

### ISSUE THREAD

**Issue by Skeyelab** [nickelser/zhong#18]
Once I add the zhong stuff to my routes file, my application breaks.  Any insight?

routes.rb
```
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  require 'zhong/web'
  mount Zhong::Web => "/zhong"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "admin/desks#index"
end
```

```
➜  ZD-DataCollector git:(zhong) ✗ rails s
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- sinatra/base (LoadError)
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/zhong-0.2.2/lib/zhong/web.rb:3:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config/routes.rb:8:in `block in <top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config/routes.rb:1:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config/environment.rb:5:in `<top (required)>'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config.ru:3:in `require_relative'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config.ru:3:in `block in <main>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config.ru:in `new'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config.ru:in `<main>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/server.rb:59:in `app'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/server.rb:124:in `log_to_stdout'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/server.rb:77:in `start'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'```

**Comment by nickelser** [comment]
@Skeyelab are you including Sinatra in your Gemfile? Something like:

```ruby
gem "sinatra", require: false
```

should be sufficient. If that fixes things, I will update the README.

**Comment by Skeyelab** [comment]
now I'm getting a new one

```
➜  ZD-DataCollector git:(zhong) ✗ rails c
/Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- rack/showexceptions (LoadError)
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/zhong-0.2.2/lib/zhong/web.rb:3:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config/routes.rb:8:in `block in <top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `instance_exec'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:389:in `eval_block'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/actionpack-5.0.2/lib/action_dispatch/routing/route_set.rb:371:in `draw'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config/routes.rb:1:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/file_update_checker.rb:77:in `execute'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application/finisher.rb:119:in `block in <module:Finisher>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:30:in `run'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/edahl/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application.rb:352:in `initialize!'
	from /Users/edahl/Documents/ruby/rails/ZD-DataCollector/config/environment.rb:5:in `<top (required)>'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `block in require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:293:in `require'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/application.rb:328:in `require_environment!'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:157:in `require_application_and_environment!'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:77:in `console'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/edahl/.rvm/gems/ruby-2.3.1@ZD-DataCollector/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by nickelser** [comment]
Your version of rack might be outdated, given https://github.com/sinatra/sinatra/issues/1055?

**Comment by nickelser** [comment]
closing this due to lack of repro & documentation fixes!
