### ISSUE TITLE
Issue with Rails 7.0.1

### ISSUE THREAD

**Issue by dbourguignon** [nickelser/zhong#40]
Testing an upgrade one of our app to Rails 7.0.1
We noticed a crash when starting zhong process (see below for stack trace)

This seems related to this [issue](https://github.com/rails/rails/issues/43851) on Rails.

I've tested manually to add a 

`require "active_support"` in zhong.rb and it seems to work, but I'm not sure it's the way to go.

```shell
bundle exec zhong zhong.rb
You can remove `require 'dalli/cas/client'` as this code has been rolled into the standard 'dalli/client'.
/Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:103:in `backend='
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/duration.rb:3:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/core_ext/time/calculations.rb:3:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/core_ext/time.rb:4:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/core_ext/time.rb:4:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/time.rb:12:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/activesupport-7.0.1/lib/active_support/time.rb:12:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/zhong-0.3.0/lib/zhong.rb:7:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/zhong-0.3.0/lib/zhong.rb:7:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/zhong-0.3.0/bin/zhong:5:in `require'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/gems/zhong-0.3.0/bin/zhong:5:in `<top (required)>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/bin/zhong:23:in `load'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/bin/zhong:23:in `<main>'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/bin/ruby_executable_hooks:22:in `eval'
	from /Users/davidbourguignon/.rvm/gems/ruby-3.0.1@drivy-rangers/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by dbourguignon** [comment]
Happy to provide a PR if you think it's the correct way to do it
